apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: mongo
  name: mongo
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    run: mongo
  type: NodePort
status:
  loadBalancer: {}
