apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: nodeclient
  name: nodeclient
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nodeclient
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: nodeclient
    spec:
      containers:
      - image: nodeclient:dev-latest
        name: nodeclient
        ports:
        - containerPort: 8081
        resources: {}
        imagePullPolicy: Never
        volumeMounts:
        - mountPath: /usr/src/app/website/
          name: nodeclient-volume
      volumes:
      - name: nodeclient-volume
        hostPath:
          path: /Users/.minikube-mounts/nodeclient
status: {}
