apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: nodeserver
  name: nodeserver
spec:
  ports:
  - port: 1337
    protocol: TCP
    targetPort: 1337
  selector:
    run: nodeserver
  type: NodePort
status:
  loadBalancer: {}
