apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: nodeclient
  name: nodeclient
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    run: nodeclient
  type: NodePort
status:
  loadBalancer: {}
