apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: nodehttp1
  name: nodehttp1
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    run: nodehttp1
  type: NodePort
status:
  loadBalancer: {}
